#3
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  namespace: rails-app
spec:
  selector:
    matchLabels:
      app: redis
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        tier: backend
    spec:
	  containers:
	  - name: redis
		image: redis:7.0
		ports:
		- containerPort: 6379
		volumeMounts:
		- mountPath: /var/lib/redis/data
		  name: drkiq-redis
	  volumes:
		- name: drkiq-redis
		  hostPath:
			path: /var/lib/redis/data
