#6
apiVersion: v1
kind: Pod
metadata:
  name: sidekiq
  namespace: rails-app
spec:
  containers:
  - name: sidekiq
    image: $DOCKER_USERNAME/dockerizing-ruby-sidekiq:latest
    command: ["/bin/sh", "-c", "bundle exec sidekiq"]
	volumeMounts:
	- name: env-file
      mountPath: "/.env"
      readOnly: true
  volumes:
    - name: env-file
      configMap:
        name: env-file	
